### ISSUE TITLE
camfr_PIL.py

### ISSUE THREAD

**Issue by kitchenknif** [demisjohn/CAMFR#1]
Several uses of numpy.oldnumeric.mlab

**Comment by demisjohn** [comment]
Looks like this fork has attempted to fix this: https://github.com/jtambasco/camfr/commit/78f92f1acd09a40ffc9b800d15721989714d218f
maybe see if a Pull Request is in order.

**Comment by demisjohn** [comment]
I've also fixed this, but by upgrading to PILLOW instead of using the defunct PIL.
https://github.com/demisjohn/CAMFR/commit/a138e8ee793fb4d7c79c4da9cd85a5b24e223a5b
Let me know if you'd like me to submit a pull request.  Since you last worked on this repo 2 years ago, I assume I should just keep working on my fork (I have immediate use for it), and not submit a pull request.

**Comment by kitchenknif** [comment]
Yeah,
I don't have an immediate use for CAMFR at the moment, my work has steered away from it.

**Comment by demisjohn** [comment]
fixed in a138e8ee793fb4d7c79c4da9cd85a5b24e223a5b, upgraded to use PILLOW since PIL is deprecated.
Eventually will just use Matplotlib for everything anyway.
